name: "Build ConClar Docker image for Deploy"

on:
  push:
    branches:
      #- main
      #- staging
      - development

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_name

      - name: Ubuntu GitHub Actions environment variables List
        run: env
