name: "Build ConClar Docker image for Deploy"

on:
  push:
    branches:
      #- main
      #- staging
      - development

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_name

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Define the repository labels
        run: |
          echo "CONTAINER_TEST_REPOSITORY=${{ steps.login-ecr.outputs.registry }}/guide:ci-${{ github.sha }}" >> $GITHUB_ENV
          echo "CONTAINER_DEPLOY_REPOSITORY=${{ steps.login-ecr.outputs.registry }}/guide:${{ steps.extract_name.outputs.branch }}" >> $GITHUB_ENV

      - name: Ubuntu GitHub Actions environment variables List
        run: env
