name: "Build ConClar Docker image for Deploy"

on:
  push:
    branches:
      #- main
      #- staging
      - development

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
