name: "Build ConClar Docker image for Deploy"

on:
  push:
    branches:
      #- main
      #- staging
      - development

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_name

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Define the repository labels
        run: |
          echo "CONTAINER_TEST_REPOSITORY=${{ steps.login-ecr.outputs.registry }}/conclar:ci-${{ github.sha }}" >> $GITHUB_ENV
          echo "CONTAINER_DEPLOY_REPOSITORY=${{ steps.login-ecr.outputs.registry }}/conclar:${{ steps.extract_name.outputs.branch }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Ubuntu GitHub Actions environment variables List
        run: env

      - name: Build the image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            NODE_ENV=development
          push: false
          load: true
          # target: development
          tags: "${{ env.CONTAINER_TEST_REPOSITORY }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Ubuntu GitHub Actions environment variables List
        run: env
